### ISSUE TITLE
Upgrade to RC 0.13

### ISSUE THREAD

**Issue by jayengee** [BloomBoard-Research/influxdb#1]
## Requirements ##
The purpose of forking this repo was to allow for us to create a build of influxdb, pointing to a specific version of influxdb. In this case, we need to point to RC 0.13 once it is released - this release candidate contains the code fix necessary for supporting `distinct` queries on string fields, and thus is necessary for singular reporting.

## Tasks ##
- [ ] Repoint influx image to RC 0.13
- [ ] Rebuild and redeploy
- [ ] Test via `analytics-service`
